.\ps_InsertPointers.ps1 cardhero1-script.txt_002.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_003.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_004.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_005.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_006.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_007.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_008.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_009.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_010.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_011.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_012.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_013.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_014.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_015.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_019.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_020.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_021.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_022.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_023.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_024.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_025.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_026.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_027.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_028.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_029.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_030.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_031.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_032.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_033.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_034.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_035.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_036.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_037.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_038.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_039.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_040.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_041.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_042.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_043.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_044.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_045.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_046.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_047.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_048.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_049.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_050.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_051.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_052.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_053.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_054.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_055.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_056.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_057.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_058.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_059.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_060.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_061.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_062.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_063.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_064.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_078.txt
.\ps_InsertPointers.ps1 cardhero1-script.txt_079.txt
